root: true
parser: "@typescript-eslint/parser"
plugins: 
  - "@typescript-eslint"
  - "prettier"
extends:
  - plugin:prettier/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
rules: 
  prettier/prettier: warn
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-unused-vars': [warn, { 'argsIgnorePattern': '^_' }]